services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - vaultwarden_data:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - DATABASE_URL=postgresql://vaultwarden:password@db:5432/vaultwarden
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:443"
    volumes:
      - ./ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      - ./ssl/:/etc/nginx/ssl:ro
    depends_on:
      - vaultwarden
  db:
    image: postgres:17-alpine
    container_name: vaultwarden-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=vaultwarden
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vaultwarden
    volumes:
      - vaultwarden_db_data:/var/lib/postgresql/data
volumes:
  vaultwarden_data:
  vaultwarden_db_data:
